### ISSUE TITLE
data label empty error

### ISSUE THREAD

**Issue by atticcas** [precedenceguo/mx-rcnn#46]
`    test_data = TestLoader(roidb, batch_size=1, shuffle=shuffle, has_rpn=True)
`
Hi 

I have just tried your latest repo with Your version of MXNET(2 commit behind master)
Have you changed the data loader completely? or there could be a bug here.
Where test_data.provide_label always return empty.
I did some digging and made it work replacing provide_label to provide_data
and the program works.(not sure about the result, still testing)

Also it seems like with the newest MXnet(0.9) the processing speed slowed down?
With this repo's code I see around 20% speed drop

maybe I am doing settings wrrong

Thanks!

**Comment by precedenceguo** [comment]
Thank you for feedback.

I set test_data.provide_label to None (previously it is []) in order to comply with new definition of nnvm mxnet (0.9). I seem not to have any problem testing.
You mean you must set it to provide_data in order to test?

I am working on the standard detection io which caused the speed to go down. The result is still the same according to my experiment.
